import React, { useState, useEffect } from 'react';
import { 
  Tv, 
  Clock, 
  HelpCircle, 
  ArrowRight, 
  ArrowLeft, 
  CheckCircle, 
  XCircle, 
  RotateCcw, 
  Award,
  BookOpen,
  Monitor,
  Flame,
  Gamepad2,
  FileText
} from 'lucide-react';
import { syncFetchAllCbtExams } from '../../../lib/sync';

interface Question {
  id: number;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

interface HighScore {
  subject: string;
  score: number;
  total: number;
  percentage: number;
  date: string;
}

export default function CbtExam() {
  const [phase, setPhase] = useState<'config' | 'exam' | 'result'>('config');
  const [selectedSubject, setSelectedSubject] = useState<string>('Mathematics');
  const [studentClass, setStudentClass] = useState<string>('JSS 1');
  const [availableModules, setAvailableModules] = useState<{ subject: string; class: string; description?: string }[]>([]);
  
  // Quiz running states
  const [questions, setQuestions] = useState<Question[]>([]);
  const [currentIdx, setCurrentIdx] = useState(0);
  const [selectedAnswers, setSelectedAnswers] = useState<Record<number, number>>({});
  const [timeRemaining, setTimeRemaining] = useState(300); // 5 minutes standard countdown
  const [highScores, setHighScores] = useState<HighScore[]>([]);

  // Ticking effect
  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (phase === 'exam' && timeRemaining > 0) {
      timer = setInterval(() => {
        setTimeRemaining(prev => {
          if (prev <= 1) {
            clearInterval(timer);
            submitExam();
            return 0;
          }
          return prev - 1;
        });
      }, 1005);
    }
    return () => clearInterval(timer);
  }, [phase, timeRemaining]);

  const [triggerRescan, setTriggerRescan] = useState(0);

  // Load student profile & find their assigned class limits
  useEffect(() => {
    const savedGrades = localStorage.getItem('ff_student_report_card');
    let loadedClass = 'JSS 1';
    if (savedGrades) {
      try {
        const parsed = JSON.parse(savedGrades);
        // Find class from any active reporting terms
        if (parsed['1st'] && parsed['1st'].class) {
          loadedClass = parsed['1st'].class;
        } else if (parsed['2nd'] && parsed['2nd'].class) {
          loadedClass = parsed['2nd'].class;
        } else if (parsed.class) {
          loadedClass = parsed.class;
        }
      } catch (e) {}
    }
    setStudentClass(loadedClass);

    // Initial load of High Scores
    const saved = localStorage.getItem('ff_cbt_highscores');
    if (saved) {
      setHighScores(JSON.parse(saved));
    }

    // In background, fetch all available CBT exam settings from Supabase to sync in real-time
    syncFetchAllCbtExams().then(() => {
      setTriggerRescan(prev => prev + 1);
    });
  }, []);

  // Scan local directories and browser storage to locate assigned/posted cbt examinations
  useEffect(() => {
    const scannedModules: { subject: string; class: string; description: string }[] = [];

    // Scan localStorage for custom posted CBT indices matching this student's class target
    for (let i = 0; i < localStorage.length; i++) {
      const key = localStorage.key(i);
      if (key && key.startsWith('ff_cbt_') && key.endsWith('_questions') && key !== 'ff_cbt_highscores') {
        // E.g. ff_cbt_yoruba_jss_1_questions or ff_cbt_mathematics_questions -> clean string for extraction
        const clean = key.replace('ff_cbt_', '').replace('_questions', '');
        const parts = clean.split('_');
        if (parts.length >= 2) {
          const clsPart = parts[parts.length - 1].toUpperCase(); // E.g., "JSS1" or "SS3"
          const clsFormatted = clsPart.startsWith('JSS') 
            ? `JSS ${clsPart.replace('JSS', '')}` 
            : clsPart.startsWith('SSS') 
              ? `SSS ${clsPart.replace('SSS', '')}` 
              : clsPart.startsWith('SS')
                ? `SS ${clsPart.replace('SS', '')}`
                : clsPart;

          const subPart = parts.slice(0, parts.length - 1).map(p => p.charAt(0).toUpperCase() + p.slice(1)).join(' ');
          
          if (clsFormatted.toLowerCase().replace(/\s+/g, '') === studentClass.toLowerCase().replace(/\s+/g, '')) {
            scannedModules.push({
              subject: subPart,
              class: studentClass,
              description: `Customized diagnostic test dynamically generated by subject mentor for Class ${clsFormatted}.`
            });
          }
        }
      }
    }

    // Rely purely on real scanned custom modules matching the student's class
    setAvailableModules(scannedModules);
  }, [studentClass, triggerRescan]);

  const getSubjectQuestions = (subj: string): Question[] => {
    const key = `ff_cbt_${subj.toLowerCase().replace(/\s+/g, '_')}_${studentClass.toLowerCase().replace(/\s+/g, '_')}_questions`;
    const saved = localStorage.getItem(key);
    if (saved) {
      return JSON.parse(saved);
    }
    
    // Legacy fallback parameters for defaults
    const legacyKey = subj === 'Mathematics' ? 'ff_cbt_mathematics_questions' : subj === 'Physics' ? 'ff_cbt_physics_questions' : '';
    if (legacyKey) {
      const savedLegacy = localStorage.getItem(legacyKey);
      if (savedLegacy) return JSON.parse(savedLegacy);
    }

    return [];
  };

  const startExam = (subject: string) => {
    setSelectedSubject(subject);
    setQuestions(getSubjectQuestions(subject));
    setCurrentIdx(0);
    setSelectedAnswers({});
    setTimeRemaining(300);
    setPhase('exam');
  };

  const handleSelectOption = (questionId: number, optionIdx: number) => {
    setSelectedAnswers(prev => ({
      ...prev,
      [questionId]: optionIdx
    }));
  };

  const submitExam = () => {
    setPhase('result');

    // Calculate score
    const targetQs = getSubjectQuestions(selectedSubject);
    let correctCount = 0;
    targetQs.forEach(q => {
      if (selectedAnswers[q.id] === q.correctIndex) {
        correctCount += 1;
      }
    });

    const percent = Math.round((correctCount / (targetQs.length || 1)) * 100);
    const newRecord: HighScore = {
      subject: selectedSubject,
      score: correctCount,
      total: targetQs.length,
      percentage: percent,
      date: new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: '2-digit' })
    };

    const updatedScores = [newRecord, ...highScores].slice(0, 10);
    setHighScores(updatedScores);
    localStorage.setItem('ff_cbt_highscores', JSON.stringify(updatedScores));

    // Link dynamic Award Achievements tracking!
    if (percent === 100) {
      // Unlocked CBT Champion badge automatically!
      const currentAchievements = localStorage.getItem('ff_student_achievements');
      if (currentAchievements) {
        try {
          const parsed = JSON.parse(currentAchievements);
          const update = parsed.map((a: any) => {
            if (a.id === 'AW-02') {
              return { ...a, unlocked: true, unlockedDate: newRecord.date };
            }
            return a;
          });
          localStorage.setItem('ff_student_achievements', JSON.stringify(update));
        } catch (e) {}
      }
    }
  };

  const formatTime = (secs: number) => {
    const min = Math.floor(secs / 60);
    const remaining = secs % 60;
    return `${min}:${remaining < 10 ? '0' : ''}${remaining}`;
  };

  // Score stats for presentation
  const finalScore = questions.filter(q => selectedAnswers[q.id] === q.correctIndex).length;
  const finalPercent = Math.round((finalScore / (questions.length || 1)) * 100);

  return (
    <div className="space-y-8 font-sans pb-16">
      
      {/* Top title bar */}
      <div className="bg-white rounded-3xl border border-slate-200/80 shadow-sm p-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="space-y-1">
          <div className="flex items-center gap-2">
            <span className="p-2 rounded-xl bg-primary/10 text-primary">
              <Tv size={20} />
            </span>
            <h2 className="text-xl font-extrabold text-slate-800 tracking-tight uppercase">Computer-Based Testing (CBT) Hub</h2>
          </div>
          <p className="text-xs text-slate-500">
            Hone examination speeds under timed national standards. Results are scored and detailed step-by-step corrections are generated instantly.
          </p>
        </div>
      </div>

      {phase === 'config' && (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          
          {/* Diagnostic Subject Select Card */}
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white rounded-3xl border border-slate-200 p-6 md:p-8 space-y-6 shadow-sm">
              <h3 className="text-sm font-black text-slate-800 uppercase tracking-wider border-b border-slate-105 pb-3">Available CBT Practice Modules</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {availableModules.length === 0 ? (
                  <div className="col-span-1 md:col-span-2 text-center py-12 space-y-3">
                    <div className="text-3xl">💻</div>
                    <p className="text-xs font-black uppercase text-slate-800 tracking-wider">No CBT practice modules available</p>
                    <p className="text-[10px] text-slate-450 max-w-sm mx-auto font-semibold leading-relaxed">No computer-based tests or continuous practice assessments have been published/assigned for Class {studentClass} yet.</p>
                  </div>
                ) : (
                  availableModules.map((mod, mIdx) => (
                    <div key={mIdx} className="p-6 border border-slate-150 bg-slate-50/50 rounded-2xl hover:border-slate-350 hover:bg-white transition-all flex flex-col justify-between h-[210px] group">
                      <div className="space-y-2 text-left">
                        <span className="bg-primary/10 text-primary text-[9px] font-black uppercase px-2.5 py-1 rounded inline-block font-mono tracking-wider">
                          {mod.class} Assessment Pool
                        </span>
                        <h4 className="text-sm font-bold text-slate-800 uppercase">{mod.subject} Practice</h4>
                        <p className="text-[11px] text-slate-500 leading-relaxed h-[65px] overflow-hidden line-clamp-3">
                          {mod.description || "Diagnostics continuous assessment questions curated by institutional subject instructor."}
                        </p>
                      </div>
                      <button 
                        onClick={() => startExam(mod.subject)}
                        className="w-full mt-4 bg-primary text-white py-3 rounded-lg text-[10px] font-black uppercase tracking-widest text-center shadow-md shadow-primary/15 hover:bg-primary/95 transition-all flex items-center justify-center gap-1.5 cursor-pointer"
                      >
                        Start Exam Session <ArrowRight size={12} />
                      </button>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>

          {/* High Score Records */}
          <div>
            <div className="bg-white rounded-3xl border border-slate-200 p-6 space-y-4 shadow-sm">
              <h3 className="text-xs font-black text-slate-800 uppercase tracking-widest border-b border-slate-100 pb-2.5">High Scores History</h3>
              
              <div className="space-y-3">
                {highScores.length === 0 ? (
                  <div className="text-xs text-slate-400 font-semibold text-center py-8">
                    No CBT records available.
                  </div>
                ) : (
                  highScores.map((score, index) => (
                    <div key={index} className="p-3.5 border border-slate-150 rounded-xl flex items-center justify-between gap-3 bg-slate-50/70">
                      <div>
                        <h4 className="text-[11px] font-black text-slate-800 uppercase leading-snug">{score.subject} Practice</h4>
                        <span className="text-[9px] text-slate-400 font-mono">Date: {score.date}</span>
                      </div>
                      <div className="text-right">
                        <span className="font-mono text-xs font-black text-primary block">{score.score} / {score.total}</span>
                        <span className="text-[9px] font-black text-emerald-600 font-mono">{score.percentage}%</span>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          </div>

        </div>
      )}

      {phase === 'exam' && (
        <div className="bg-white border-2 border-slate-200 rounded-[32px] p-6 md:p-10 shadow-md space-y-8 relative overflow-hidden select-none">
          
          {/* Sticky Timed banner bar */}
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 border-b border-slate-150 pb-5">
            <div>
              <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest font-mono">SUBJECT EXAM IN PROGRESS</span>
              <h3 className="text-base font-black text-slate-850 uppercase tracking-tight">{selectedSubject} Stream Drills</h3>
            </div>

            <div className={`flex items-center gap-2 p-3 rounded-2xl border font-mono font-black text-sm uppercase shrink-0 ${
              timeRemaining < 60 
                ? 'bg-rose-50 text-rose-600 border-rose-200 animate-pulse' 
                : 'bg-primary/5 text-primary border-primary/10'
            }`}>
              <Clock size={16} />
              <span>Time Remaining: {formatTime(timeRemaining)}</span>
            </div>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            
            {/* Question Card display */}
            <div className="lg:col-span-2 space-y-6 text-xs text-left">
              <div className="space-y-4">
                <div className="flex justify-between items-center bg-slate-50 p-3 rounded-xl border border-slate-150/70 text-[10px] font-black text-slate-500 uppercase tracking-wider">
                  <span>Question {currentIdx + 1} of {questions.length}</span>
                  <span>Worth 5.0 Marks</span>
                </div>

                <p className="text-sm font-bold text-slate-800 leading-relaxed font-sans">{questions[currentIdx]?.question}</p>
              </div>

              {/* Multiple Choice interactive selection */}
              <div className="space-y-3 pt-2">
                {questions[currentIdx]?.options.map((opt, oIdx) => {
                  const isChecked = selectedAnswers[questions[currentIdx].id] === oIdx;
                  return (
                    <div 
                      key={oIdx}
                      onClick={() => handleSelectOption(questions[currentIdx].id, oIdx)}
                      className={`p-4 border rounded-2xl hover:border-slate-350 cursor-pointer transition-all flex items-center justify-between text-xs font-semibold ${
                        isChecked 
                          ? 'border-primary bg-blue-50/20 text-primary font-bold' 
                          : 'border-slate-150 bg-white hover:bg-slate-50/50'
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className={`w-6 h-6 rounded-lg font-mono font-black text-[11px] flex items-center justify-center border transition-colors ${
                          isChecked 
                            ? 'bg-primary text-white border-primary' 
                            : 'bg-slate-50 text-slate-500'
                        }`}>
                          {String.fromCharCode(65 + oIdx)}
                        </span>
                        <span>{opt}</span>
                      </div>

                      <div className={`w-4 h-4 rounded-full border flex items-center justify-center shrink-0 ${
                        isChecked ? 'border-primary' : 'border-slate-300'
                      }`}>
                        {isChecked && <div className="w-2 h-2 bg-primary rounded-full"></div>}
                      </div>
                    </div>
                  );
                })}
              </div>

              {/* Navigation trigger button rows */}
              <div className="flex justify-between items-center pt-6 border-t border-slate-100">
                <button
                  disabled={currentIdx === 0}
                  onClick={() => setCurrentIdx(prev => prev - 1)}
                  className="bg-slate-50 hover:bg-slate-100 disabled:opacity-40 border border-slate-200 px-5 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest inline-flex items-center gap-1.5 cursor-pointer disabled:cursor-not-allowed"
                >
                  <ArrowLeft size={12} /> Previous Question
                </button>

                {currentIdx < questions.length - 1 ? (
                  <button
                    onClick={() => setCurrentIdx(prev => prev + 1)}
                    className="bg-slate-900 border text-white px-5 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest inline-flex items-center gap-1.5 cursor-pointer"
                  >
                    Next Question <ArrowRight size={12} />
                  </button>
                ) : (
                  <button
                    onClick={submitExam}
                    className="bg-emerald-600 hover:bg-emerald-650 text-white px-6 py-3 rounded-xl text-[10px] font-black uppercase tracking-widest inline-flex items-center gap-1.5 cursor-pointer shadow-md shadow-emerald-600/15"
                  >
                    Submit Test Paper
                  </button>
                )}
              </div>
            </div>

            {/* Questions tracker sidebar grid */}
            <div>
              <div className="bg-slate-50 rounded-2xl border border-slate-200/80 p-5 space-y-4">
                <h4 className="text-[10px] font-black text-slate-450 uppercase tracking-widest">Question Tracker Board</h4>
                <div className="grid grid-cols-5 gap-2.5">
                  {questions.map((q, idx) => {
                    const isSelected = currentIdx === idx;
                    const isAnswered = selectedAnswers[q.id] !== undefined;
                    return (
                      <button
                        key={q.id}
                        onClick={() => setCurrentIdx(idx)}
                        className={`h-9 rounded-xl font-mono font-black text-center text-xs border transition-all ${
                          isSelected 
                            ? 'bg-primary text-white border-primary scale-[1.08]' 
                            : isAnswered 
                              ? 'bg-emerald-50 text-emerald-700 border-emerald-250' 
                              : 'bg-white text-slate-500 border-slate-200 hover:bg-slate-50'
                        }`}
                      >
                        {idx + 1}
                      </button>
                    );
                  })}
                </div>
                <div className="text-[9px] text-slate-400 font-bold uppercase tracking-wider space-y-1.5 border-t border-slate-200 pt-3">
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 bg-primary rounded-md"></span>
                    <span>Active viewing question</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 bg-emerald-50 border border-emerald-200 rounded-md"></span>
                    <span>Answer selected</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <span className="w-2.5 h-2.5 bg-white border border-slate-200 rounded-md"></span>
                    <span>Unanswered</span>
                  </div>
                </div>
              </div>
            </div>

          </div>
        </div>
      )}

      {phase === 'result' && (
        <div className="space-y-8 select-none">
          
          {/* Feedback details scorecard */}
          <div className="bg-white border-2 border-slate-200 rounded-[32px] p-8 md:p-10 shadow-md text-center max-w-2xl mx-auto space-y-6">
            <div className="w-16 h-16 bg-primary/10 text-primary border-2 border-accent rounded-full flex items-center justify-center mx-auto text-3xl font-bold animate-bounce">
              🏆
            </div>

            <div className="space-y-1.5">
              <span className="text-[10px] font-black text-slate-400 uppercase tracking-widest">DIAGNOSTIC TEST COMPLETE RESULT</span>
              <h3 className="text-xl font-black text-slate-800 uppercase tracking-tight">{selectedSubject} Study drill Evaluation</h3>
              <p className="text-xs text-slate-500">Continuous Assessment testing successfully processed by automatic AI grader.</p>
            </div>

            <div className="grid grid-cols-2 gap-4 max-w-sm mx-auto p-4 bg-slate-50 rounded-2xl border border-slate-150/70">
              <div className="text-center font-mono">
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider block">SCORE RATING</span>
                <span className="text-xl font-black text-slate-800">{finalScore} / {questions.length}</span>
              </div>
              <div className="text-center font-mono border-l border-slate-200">
                <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider block">PERCENTAGE INDEX</span>
                <span className="text-xl font-black text-emerald-600">{finalPercent}%</span>
              </div>
            </div>

            <div>
              {finalPercent >= 80 ? (
                <span className="bg-green-50 text-green-700 border border-green-200 text-xs font-black px-4 py-2 rounded-xl uppercase">✓ OUTSTANDING ACHIEVEMENT</span>
              ) : finalPercent >= 50 ? (
                <span className="bg-blue-50 text-blue-700 border border-blue-200 text-xs font-black px-4 py-2 rounded-xl uppercase">✓ PASS RECORD RECEIVED</span>
              ) : (
                <span className="bg-rose-50 text-rose-700 border border-rose-200 text-xs font-black px-4 py-2 rounded-xl uppercase">❌ FOCUS NEEDED</span>
              )}
            </div>

            <div className="pt-2">
              <button 
                onClick={() => setPhase('config')}
                className="bg-primary hover:bg-opacity-95 text-white font-bold uppercase tracking-widest text-xs py-3.5 px-6 rounded-xl shadow-lg shadow-primary/15"
              >
                Close & Return To Lobby
              </button>
            </div>
          </div>

          {/* Corrections spreadsheet list */}
          <div className="bg-white rounded-[32px] border border-slate-200 p-6 md:p-8 space-y-6 shadow-sm text-xs text-left">
            <h3 className="text-sm font-black text-slate-800 uppercase tracking-wider border-b border-slate-105 pb-3">Educational Corrections & Explanations</h3>

            <div className="space-y-6">
              {questions.map((q, qIdx) => {
                const userAnsIdx = selectedAnswers[q.id];
                const isCorrect = userAnsIdx === q.correctIndex;
                return (
                  <div key={q.id} className="p-5 border border-slate-150 rounded-2xl bg-slate-50/45 space-y-4">
                    <div className="flex justify-between items-start gap-4 flex-wrap border-b border-dashed border-slate-200 pb-2.5">
                      <span className="font-extrabold text-[11px] text-slate-800 uppercase">Question {qIdx + 1} Assessment</span>
                      <div>
                        {isCorrect ? (
                          <span className="bg-green-50 text-green-700 border border-green-150 px-2 py-0.5 rounded text-[9px] font-black uppercase flex items-center gap-1"><CheckCircle size={10} /> Correct</span>
                        ) : (
                          <span className="bg-rose-50 text-rose-750 border border-rose-150 px-2 py-0.5 rounded text-[9px] font-black uppercase flex items-center gap-1"><XCircle size={10} /> Incorrect</span>
                        )}
                      </div>
                    </div>

                    <p className="font-bold text-slate-800 leading-relaxed">{q.question}</p>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-xs leading-relaxed max-w-2xl font-medium pt-1.5">
                      <div className="p-3.5 bg-white border border-slate-150 rounded-xl space-y-0.5">
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider block">Your Selected Answer:</span>
                        <p className={isCorrect ? 'text-green-700 font-extrabold' : 'text-rose-700 font-extrabold'}>
                          {userAnsIdx !== undefined ? `${String.fromCharCode(65 + userAnsIdx)}. ${q.options[userAnsIdx]}` : 'Unanswered'}
                        </p>
                      </div>

                      <div className="p-3.5 bg-white border border-slate-150 rounded-xl space-y-0.5">
                        <span className="text-[9px] font-black text-slate-400 uppercase tracking-wider block">Correct Option Mark:</span>
                        <p className="text-green-700 font-extrabold">
                          {String.fromCharCode(65 + q.correctIndex)}. {q.options[q.correctIndex]}
                        </p>
                      </div>
                    </div>

                    <div className="p-4 bg-blue-50/45 border border-blue-150/50 rounded-xl text-slate-650 leading-relaxed font-semibold">
                      <span className="text-[9px] font-black text-primary uppercase block tracking-wider mb-0.5">Pedagogical Step Explanations:</span>
                      "{q.explanation}"
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

        </div>
      )}

    </div>
  );
}
